name: Build Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild (adds MSBuild to PATH)
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages (if .sln exists)
        shell: pwsh
        run: |
          if (Test-Path -Path "mimikatz.sln") {
            Write-Host "Found mimikatz.sln — running nuget restore"
            nuget restore mimikatz.sln
          } else {
            Write-Host "No solution file found — skipping nuget restore"
          }

      - name: Build with MSBuild
        shell: pwsh
        run: |
          if (Test-Path -Path "mimikatz.sln") {
            msbuild mimikatz.sln /p:Configuration=Release /p:Platform=x64 /m
          } else {
            Write-Host "No solution file found — you may need to adjust the path"
          }

      - name: Collect build artifacts
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path artifacts -Force | Out-Null
          if (Test-Path -Path "./MyProject/bin/Release") {
            robocopy .\MyProject\bin\Release .\artifacts /E
          } else {
            Write-Host "No build outputs found at ./MyProject/bin/Release"
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe-artifacts
          path: artifacts
